import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

const FRONTEND = join(dirname(fileURLToPath(import.meta.url)), "../../..");

const GENERATED = [
  "src/data/wireframe/snapshot.ts",
  "src/data/wireframe/taxonomies.ts",
  "src/data/wireframe/creators.ts",
  "src/data/wireframe/prompts.ts",
  "src/data/wireframe/models.ts",
  "src/data/wireframe/collections.ts",
  "evidence/fixture-extraction.md",
];

function fingerprint(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const file of GENERATED) {
    out[file] = createHash("sha256").update(readFileSync(join(FRONTEND, file))).digest("hex");
  }
  return out;
}

describe("pnpm extract:wireframe", () => {
  it("is idempotent: re-running it reproduces the committed fixture byte for byte", () => {
    const before = fingerprint();
    execFileSync("node", ["scripts/extract-wireframe.mjs"], { cwd: FRONTEND, stdio: "pipe" });
    expect(fingerprint()).toEqual(before);
    // A second run must be stable too — no timestamps, no nondeterministic ordering.
    execFileSync("node", ["scripts/extract-wireframe.mjs"], { cwd: FRONTEND, stdio: "pipe" });
    expect(fingerprint()).toEqual(before);
  }, 60_000);

  it("marks every generated module as generated", () => {
    for (const file of GENERATED) {
      if (file.endsWith(".md")) continue;
      const head = readFileSync(join(FRONTEND, file), "utf8").split("\n")[0];
      expect(head).toBe("// GENERATED by scripts/extract-wireframe.mjs — do not edit.");
    }
  });

  it("keeps the hand-written fixture modules out of the generator's reach", () => {
    for (const file of ["src/data/wireframe/index.ts"]) {
      const head = readFileSync(join(FRONTEND, file), "utf8").split("\n")[0];
      expect(head).not.toContain("GENERATED by");
    }
  });
});
