import {
  handleCloudflareCmsRequest,
  type CloudflareRequestExecutionContext,
} from './runtime/cloudflareRequestScopedPostgres.ts'

// Generated by the reviewed OpenNext build before Wrangler resolves this
// tracked entrypoint.
// @ts-expect-error `.open-next` is intentionally absent from clean source checkouts.
import openNextWorker from '../.open-next/worker.js'

// Keep OpenNext's Durable Object exports available if a later reviewed cache
// configuration enables them.
// @ts-expect-error `.open-next` is intentionally absent from clean source checkouts.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from '../.open-next/worker.js'

interface CmsWorkerEnvironment {
  readonly CMS_DATABASE_ADAPTER?: string
  readonly CMS_POSTGRES_TRANSPORT?: string
  readonly [name: string]: unknown
}

interface OpenNextWorker {
  readonly fetch: (
    request: Request,
    environment: CmsWorkerEnvironment,
    context: CloudflareRequestExecutionContext,
  ) => Promise<Response>
}

const worker = openNextWorker as OpenNextWorker

export default {
  fetch(
    request: Request,
    environment: CmsWorkerEnvironment,
    context: CloudflareRequestExecutionContext,
  ): Promise<Response> {
    return handleCloudflareCmsRequest(
      request,
      environment,
      context,
      (scopedRequest, scopedEnvironment, scopedContext) => (
        worker.fetch(scopedRequest, scopedEnvironment, scopedContext)
      ),
    )
  },
}
