'use client';
import {Shell,Picture,Actions,Words,number,type EditorialProps} from './shared';
import type {Prompt} from '@/lib/catalog/types';
function Argument({rows}:{rows:Prompt[]}){
 const chosen:Prompt[]=[];const pick=(predicate:(p:Prompt)=>boolean)=>{const p=rows.find(p=>!chosen.includes(p)&&predicate(p))||rows.find(p=>!chosen.includes(p));if(p)chosen.push(p);return p};
 const chapters=[{heading:'Look before you generate.',copy:'Start with a result. Look at the framing, the light and the details, then read the prompt that accompanies it.',prompt:pick(p=>!!p.img)}, {heading:'The details are in the words.',copy:'Some instructions read like prose. Others are structured JSON. Open the complete text to see exactly what this prompt asks for.',prompt:pick(p=>/^\s*[\[{]/.test(p.prompt))}, {heading:'Follow it back to its author.',copy:'A useful prompt has context. The source link takes you to the original post; the generation link opens this prompt’s detail page.',prompt:pick(p=>!!p.handle)}];
 const rest=rows.filter(p=>!chosen.includes(p));
 return <>{chapters.filter(c=>c.prompt).map((c,i)=><section className="ed-claim" key={c.heading}><div className="ed-argument"><p className="ed-label">{number(i)} / A closer look</p><h2>{c.heading}</h2><p>{c.copy}</p></div><article className="ed-specimen" data-prompt-id={c.prompt!.id}><div className="ed-specimen-label"><span>Specimen {number(i)}</span><span>{c.prompt!.kind} · {c.prompt!.models[0]?.label||'No model named'}</span></div><Picture prompt={c.prompt!}/><h3>{c.prompt!.title}</h3><blockquote lang={c.prompt!.language}>{c.prompt!.prompt.slice(0,640)}{c.prompt!.prompt.length>640?'…':''}</blockquote><Actions prompt={c.prompt!}/><Words prompt={c.prompt!}/></article></section>)}<section className="ed-claim ed-closing"><div className="ed-argument"><h2>{rest.length?'There is more to explore.':'The whole selection, above.'}</h2><p>{rest.length?`${rest.length} more prompts in this selection. Each title opens its full record.`:'Every prompt matching your filters is shown above.'}</p></div>{!!rest.length&&<div className="ed-running">{rest.map(p=><a key={p.id} href={p.href}>{p.title}<span aria-hidden="true"> · </span></a>)}</div>}</section></>;
}
export default function Manifesto(props:EditorialProps){return <Shell {...props} direction="manifesto" title={<>{props.task.label}<br/>begins with<br/>the words.</>} intro="The result catches your eye. The prompt tells you how it was described. Read them together, with the author’s words kept intact.">{rows=><Argument rows={rows}/>}</Shell>}
