'use client';
import {useState} from 'react';
import type {Prompt} from '@/lib/catalog/types';
import {PromptMedia} from '@/components/PromptMedia';
import {generationLabel} from '@/components/generation-label';
import {terms,type Props} from '../shared';
export type EditorialProps=Props;
export const number=(i:number)=>String(i+1).padStart(2,'0');
export function Actions({prompt}:{prompt:Prompt}){return <div className="ed-actions"><a className="ed-generate" href={prompt.href}>{generationLabel(prompt.kind)} ↗</a><a className="ed-source" href={prompt.source.url} target="_blank" rel="nofollow noopener noreferrer">{prompt.handle||'Source post'} ↗</a></div>}
export function Words({prompt,open=false}:{prompt:Prompt;open?:boolean}){return <details className="ed-words" open={open}><summary>Read the full prompt <span>{prompt.prompt.length.toLocaleString('en-US')} characters</span></summary><pre lang={prompt.language}>{prompt.prompt}</pre></details>}
export function Picture({prompt,multiple=false}:{prompt:Prompt;multiple?:boolean}){
 const frames=multiple?prompt.media.filter(m=>m.kind==='image').slice(0,3):[];
 return <div className={`ed-picture${frames.length>1?' ed-multi':''}`}>{frames.length>1?frames.map(m=><div className="ed-mount" key={m.id}><PromptMedia prompt={{...prompt,img:m.src,media:[m]}} width={900} height={900}/></div>):<div className="ed-mount">{prompt.img||prompt.media.length?<PromptMedia prompt={prompt} width={1200} height={900}/>:<p className="ed-textplate">{prompt.prompt.slice(0,400)}{prompt.prompt.length>400?'…':''}</p>}</div>}</div>;
}
export function Shell({catalog,task,variant,direction,title,intro,children}:Props&{direction:string;title:React.ReactNode;intro:string;children:(rows:Prompt[])=>React.ReactNode}){
 const [q,setQ]=useState(''),[kind,setKind]=useState('all'),[model,setModel]=useState('');
 const all=catalog.prompts.filter(p=>p.useCases.some(t=>t.slug===task.slug)),models=terms(all,'models');
 const rows=all.filter(p=>(kind==='all'||p.kind===kind)&&(!model||p.models.some(m=>m.slug===model))&&[p.title,p.prompt,p.handle].join(' ').toLowerCase().includes(q.toLowerCase()));
 return <div className={`ed-shell ed-${direction}`}><a className="ed-skip" href="#ed-results">Skip to prompts</a><header className="ed-nav"><a className="ed-brand" href="/editorial#tasks">Prompt Library</a><a href="/editorial#tasks">Browse by task</a><label><span className="vh">Explore another task</span><select value={task.slug} onChange={e=>location.assign(`/editorial/${e.target.value}?v=${variant+1}`)}>{catalog.useCases.filter(t=>t.count).map(t=><option key={t.slug} value={t.slug}>{t.label} · {t.count}</option>)}</select></label></header><main><nav className="ed-crumb ed-wrap" aria-label="Breadcrumb"><a href="/editorial#tasks">Tasks</a><span>/</span><span>{task.label}</span></nav><section className="ed-title ed-wrap"><p className="ed-label">{task.label} · {all.length} prompts</p><h1>{title}</h1><p className="ed-intro">{intro}</p></section><form className="ed-controls ed-wrap" role="search" onSubmit={e=>e.preventDefault()}><label><span className="ed-label">Search this collection</span><input type="search" value={q} autoComplete="off" spellCheck={false} placeholder={`Search ${task.label.toLowerCase()} prompts…`} onChange={e=>setQ(e.target.value)}/></label><label><span className="ed-label">Model</span><select value={model} onChange={e=>setModel(e.target.value)}><option value="">All models</option>{models.map(m=><option value={m.slug} key={m.slug}>{m.label} · {m.count}</option>)}</select></label><fieldset><legend className="ed-label">Output</legend>{['all','image','video'].map(k=><button type="button" aria-pressed={kind===k} key={k} onClick={()=>setKind(k)}>{k==='all'?'All':k==='image'?'Images':'Videos'}</button>)}</fieldset><p className="ed-count" role="status">{rows.length} of {all.length} prompts</p></form><div id="ed-results">{rows.length?children(rows):<section className="ed-empty ed-wrap"><h2>No prompts match these filters.</h2><p>Return to the full {task.label.toLowerCase()} collection.</p><button onClick={()=>{setQ('');setModel('');setKind('all')}}>Clear filters</button></section>}</div></main><footer className="ed-footer ed-wrap"><a href="/editorial#tasks">← Browse by task</a><span>Prompts belong to their authors. Every record links to its source.</span></footer></div>;
}
