'use client';
import {useState} from 'react';
import {Explorer, terms, PromptCard, PeekDialog, type Props} from '../shared';
import type {Prompt} from '@/lib/catalog/types';
function Plate({rows}:{rows:Prompt[]}){
 const [model,setModel]=useState(''),[style,setStyle]=useState(''),[peek,setPeek]=useState<Prompt|null>(null);
 const axis=(key:'models'|'styles')=>{const refs=terms(rows,key),count=rows.filter(p=>!p[key].length).length;return count?[...refs,{id:`none-${key}`,slug:'__none',label:key==='models'?'No model named':'No style named',count,href:''}]:refs};
 const models=axis('models'),styles=axis('styles');
 const cells=(m:string,s:string)=>rows.filter(p=>(!m||(m==='__none'?!p.models.length:p.models.some(r=>r.slug===m)))&&(!s||(s==='__none'?!p.styles.length:p.styles.some(r=>r.slug===s))));
 const selected=cells(model,style),peak=Math.max(1,...models.flatMap(m=>styles.map(s=>cells(m.slug,s.slug).length)));
 return <><div className="matrix-caption"><p>Model ↓ <span>×</span> Style →</p><span>Choose an intersection. Read what made it.</span></div><div className="matrix-scroll" tabIndex={0} role="region" aria-label="Models and styles matrix"><table className="task-matrix"><caption className="vh">Prompt counts by model and style within this task. A dot means no matching prompts.</caption><thead><tr><th scope="col"><button onClick={()=>{setModel('');setStyle('')}}>All combinations</button></th>{styles.map(s=><th scope="col" key={s.slug}><button aria-pressed={style===s.slug&&!model} onClick={()=>{setStyle(s.slug);setModel('')}}>{s.label}<small>{s.count}</small></button></th>)}</tr></thead><tbody>{models.map(m=><tr key={m.slug}><th scope="row"><button aria-pressed={model===m.slug&&!style} onClick={()=>{setModel(m.slug);setStyle('')}}>{m.label}<small>{m.count}</small></button></th>{styles.map(s=>{const count=cells(m.slug,s.slug).length;return <td key={s.slug}>{count?<button style={{background:`color-mix(in oklab, var(--foreground) ${4+count/peak*12}%, var(--background))`}} aria-label={`${m.label} × ${s.label}: ${count} prompts`} aria-pressed={model===m.slug&&style===s.slug} onClick={()=>{setModel(m.slug);setStyle(s.slug)}}>{count}</button>:<span className="nil" aria-label={`No prompts: ${m.label} and ${s.label}`}>·</span>}</td>})}</tr>)}</tbody></table></div><p className="matrix-legend">Fewer <span aria-hidden="true">▁ ▂ ▃ ▅</span> More <span>Prompts may appear in more than one model or style.</span></p><section className="matrix-results"><div className="section-heading"><h2>{[models.find(m=>m.slug===model)?.label,styles.find(s=>s.slug===style)?.label].filter(Boolean).join(' × ')||'All prompts'} <small>{selected.length}</small></h2>{(model||style)&&<button onClick={()=>{setModel('');setStyle('')}}>Clear selection</button>}</div><div className="result-grid">{selected.map(p=><PromptCard key={p.id} prompt={p} onOpen={()=>setPeek(p)}/>)}</div></section><PeekDialog prompt={peek} onClose={()=>setPeek(null)}/></>;
}
export default function Matrix(props:Props){return <Explorer {...props} intro="Find your combination. Explore the models and styles behind these prompts, then open the one you want to use.">{rows=><Plate key={rows.map(r=>r.id).join(',')} rows={rows}/>}</Explorer>}
