// GENERATED by scripts/extract-wireframe.mjs — do not edit.
// Source: docs/wireframes/flow-proto.html (snapshot 2026-08-20).
// Only src/lib/content/fixture-repository.ts (and tests) may import this module.

import type { Collection } from "@/lib/content/types";

export const WIREFRAME_COLLECTIONS: readonly Collection[] = [
  {
    "id": "collection:cinematic-camera",
    "slug": "cinematic-camera",
    "title": "电影感镜头合集",
    "subtitle": "镜头控制 × 电影质感",
    "rule": {
      "type": "axis-all",
      "conditions": [
        {
          "axis": "technique",
          "value": "camera-movement-shot-language"
        },
        {
          "axis": "style",
          "value": "cinematic"
        }
      ]
    }
  },
  {
    "id": "collection:multi-shot-storyboard",
    "slug": "multi-shot-storyboard",
    "title": "多镜头分镜合集",
    "subtitle": "一条提示词生成完整分镜",
    "rule": {
      "type": "axis-all",
      "conditions": [
        {
          "axis": "technique",
          "value": "multi-shot-storyboard"
        }
      ]
    }
  },
  {
    "id": "collection:transitions",
    "slug": "transitions",
    "title": "转场特效合集",
    "subtitle": "无缝转场与形变",
    "rule": {
      "type": "axis-all",
      "conditions": [
        {
          "axis": "technique",
          "value": "transition-morph-match-cut"
        }
      ]
    }
  },
  {
    "id": "collection:beauty-photorealistic",
    "slug": "beauty-photorealistic",
    "title": "美妆写实合集",
    "subtitle": "真实皮肤质感的美妆画面",
    "rule": {
      "type": "axis-all",
      "conditions": [
        {
          "axis": "useCase",
          "value": "beauty"
        },
        {
          "axis": "style",
          "value": "photorealistic"
        }
      ]
    }
  },
  {
    "id": "collection:template-prompts",
    "slug": "template-prompts",
    "title": "模板提示词合集",
    "subtitle": "带占位变量，替换即用",
    "rule": {
      "type": "regex",
      "pattern": "\\[[A-Z][A-Z0-9 _/-]{1,40}\\]|@img\\d+|@image\\d+"
    }
  },
  {
    "id": "collection:advertising",
    "slug": "advertising",
    "title": "广告创意合集",
    "subtitle": "面向投放的广告画面",
    "rule": {
      "type": "axis-all",
      "conditions": [
        {
          "axis": "useCase",
          "value": "advertising"
        }
      ]
    }
  }
];
