// GENERATED by scripts/extract-wireframe.mjs — do not edit.
// Source: docs/wireframes/flow-proto.html (snapshot 2026-08-20).
// Only src/lib/content/fixture-repository.ts (and tests) may import this module.

import type { Creator } from "@/lib/content/types";

export const WIREFRAME_CREATORS: readonly Creator[] = [
  {
    "id": "aiwithray",
    "handle": "@AIWithRay",
    "url": "https://x.com/AIWithRay",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "aiwithsarah",
    "handle": "@AIwithSarah_",
    "url": "https://x.com/AIwithSarah_",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "aiwithsynthia",
    "handle": "@AIwithSynthia",
    "url": "https://x.com/AIwithSynthia",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "aqsahere",
    "handle": "@Aqsahere_",
    "url": "https://x.com/Aqsahere_",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "arminn-ai",
    "handle": "@Arminn_Ai",
    "url": "https://x.com/Arminn_Ai",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "chillaikalan",
    "handle": "@ChillaiKalan__",
    "url": "https://x.com/ChillaiKalan__",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": 24,
    "wireframeDeclaredLikes": 3543,
    "wireframeDeclaredBookmarks": 2595
  },
  {
    "id": "haniaai12",
    "handle": "@HaniaAi12",
    "url": "https://x.com/HaniaAi12",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "higgsfield-ai",
    "handle": "@higgsfield_ai",
    "url": "https://x.com/higgsfield_ai",
    "avatarUrl": "https://pbs.twimg.com/profile_images/1906739239183630336/907a7JTU_normal.jpg",
    "followers": null,
    "wireframeDeclaredPromptCount": 78,
    "wireframeDeclaredLikes": 12533,
    "wireframeDeclaredBookmarks": 4409
  },
  {
    "id": "iqrasaifiai",
    "handle": "@IqrasaifiAI",
    "url": "https://x.com/IqrasaifiAI",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": 29,
    "wireframeDeclaredLikes": 1642,
    "wireframeDeclaredBookmarks": 1234
  },
  {
    "id": "keorunreal",
    "handle": "@KeorUnreal",
    "url": "https://x.com/KeorUnreal",
    "avatarUrl": "https://pbs.twimg.com/profile_images/2038274199379443712/HGEFaPvT_normal.jpg",
    "followers": null,
    "wireframeDeclaredPromptCount": 39,
    "wireframeDeclaredLikes": 19743,
    "wireframeDeclaredBookmarks": 12855
  },
  {
    "id": "kiber-alla",
    "handle": "@Kiber_Alla",
    "url": "https://x.com/Kiber_Alla",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "naiknelofar788",
    "handle": "@Naiknelofar788",
    "url": "https://x.com/Naiknelofar788",
    "avatarUrl": null,
    "followers": 34683,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "oggii-0",
    "handle": "@oggii_0",
    "url": "https://x.com/oggii_0",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "phedeu",
    "handle": "@PhedEU",
    "url": "https://x.com/PhedEU",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "pinodiart",
    "handle": "@PinodiArt",
    "url": "https://x.com/PinodiArt",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "rovvmut",
    "handle": "@rovvmut_",
    "url": "https://x.com/rovvmut_",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "saniaspeaks",
    "handle": "@saniaspeaks_",
    "url": "https://x.com/saniaspeaks_",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "shamsamin56",
    "handle": "@ShamsAmin56",
    "url": "https://x.com/ShamsAmin56",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "zackpaid",
    "handle": "@zackpaid",
    "url": "https://x.com/zackpaid",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "zarairahh",
    "handle": "@ZaraIrahh",
    "url": "https://x.com/ZaraIrahh",
    "avatarUrl": "https://pbs.twimg.com/profile_images/1997170504713883651/mr6aPbte_normal.jpg",
    "followers": null,
    "wireframeDeclaredPromptCount": 11,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  },
  {
    "id": "zeuuss-01",
    "handle": "@zeuuss_01",
    "url": "https://x.com/zeuuss_01",
    "avatarUrl": null,
    "followers": null,
    "wireframeDeclaredPromptCount": null,
    "wireframeDeclaredLikes": null,
    "wireframeDeclaredBookmarks": null
  }
];
