// Barrel for the wireframe fixture. HAND-WRITTEN (the individual data modules
// are generated by scripts/extract-wireframe.mjs).
//
// Import boundary: only src/lib/content/fixture-repository.ts and tests may
// import from `@/data/wireframe` — enforced by the `no-restricted-imports`
// rule in eslint.config.mjs.

export { WIREFRAME_ARTICLES, WIREFRAME_ARTICLE_CATEGORIES } from "./articles";
export { WIREFRAME_COLLECTIONS } from "./collections";
export { WIREFRAME_CREATORS } from "./creators";
export { WIREFRAME_MODELS } from "./models";
export { WIREFRAME_PROMPTS } from "./prompts";
export { WIREFRAME_SNAPSHOT } from "./snapshot";
export { WIREFRAME_TAXONOMIES } from "./taxonomies";
