// GENERATED by scripts/extract-wireframe.mjs — do not edit.
// Source: docs/wireframes/flow-proto.html (snapshot 2026-08-20).
// Only src/lib/content/fixture-repository.ts (and tests) may import this module.

import type { WireframeModelRecord } from "@/lib/content/types";

export const WIREFRAME_MODELS: readonly WireframeModelRecord[] = [
  {
    "slug": "gpt-image",
    "label": "GPT Image",
    "wireframeHasPage": false,
    "wireframeDeclaredPromptCount": 115,
    "wireframeDeclaredHotCount": 1,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "gpt-image-2",
    "label": "GPT Image 2",
    "wireframeHasPage": true,
    "wireframeDeclaredPromptCount": 50,
    "wireframeDeclaredHotCount": 4,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "higgsfield-soul",
    "label": "Higgsfield Soul",
    "wireframeHasPage": true,
    "wireframeDeclaredPromptCount": 118,
    "wireframeDeclaredHotCount": 8,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "kling",
    "label": "Kling",
    "wireframeHasPage": false,
    "wireframeDeclaredPromptCount": 76,
    "wireframeDeclaredHotCount": 3,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "nano-banana",
    "label": "Nano Banana",
    "wireframeHasPage": false,
    "wireframeDeclaredPromptCount": 218,
    "wireframeDeclaredHotCount": 0,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "nano-banana-2",
    "label": "Nano Banana 2",
    "wireframeHasPage": false,
    "wireframeDeclaredPromptCount": 40,
    "wireframeDeclaredHotCount": 11,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "nano-banana-pro",
    "label": "Nano Banana Pro",
    "wireframeHasPage": true,
    "wireframeDeclaredPromptCount": 136,
    "wireframeDeclaredHotCount": 46,
    "declaredRelatedModelSlugs": [
      "higgsfield-soul",
      "gpt-image-2"
    ],
    "declaredRelatedUseCaseSlugs": [
      "fashion",
      "beauty"
    ]
  },
  {
    "slug": "seedance",
    "label": "Seedance",
    "wireframeHasPage": false,
    "wireframeDeclaredPromptCount": 272,
    "wireframeDeclaredHotCount": 0,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "sora",
    "label": "Sora",
    "wireframeHasPage": false,
    "wireframeDeclaredPromptCount": 13,
    "wireframeDeclaredHotCount": null,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "veo",
    "label": "Veo",
    "wireframeHasPage": false,
    "wireframeDeclaredPromptCount": 26,
    "wireframeDeclaredHotCount": null,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  },
  {
    "slug": "wan",
    "label": "Wan",
    "wireframeHasPage": false,
    "wireframeDeclaredPromptCount": 11,
    "wireframeDeclaredHotCount": null,
    "declaredRelatedModelSlugs": [],
    "declaredRelatedUseCaseSlugs": []
  }
];
