// GENERATED by scripts/extract-wireframe.mjs — do not edit.
// Source: docs/wireframes/flow-proto.html (snapshot 2026-08-20).
// Only src/lib/content/fixture-repository.ts (and tests) may import this module.

import type { Snapshot } from "@/lib/content/types";

export const WIREFRAME_SNAPSHOT: Snapshot = {
  "observedAt": "2026-08-20",
  "indexVersion": "wireframe-flow-proto",
  "source": "docs/wireframes/flow-proto.html"
};
