// GENERATED by scripts/extract-wireframe.mjs — do not edit.
// Source: docs/wireframes/flow-proto.html (snapshot 2026-08-20).
// Only src/lib/content/fixture-repository.ts (and tests) may import this module.

import type { WireframeTaxonomyRecord } from "@/lib/content/types";

export const WIREFRAME_TAXONOMIES: readonly WireframeTaxonomyRecord[] = [
  {
    "id": "contentType:image",
    "axis": "contentType",
    "slug": "image",
    "label": "图片",
    "labelZh": "图片",
    "aliases": [],
    "wireframeDeclaredCount": 324,
    "appearsOn": [
      "l2"
    ]
  },
  {
    "id": "contentType:unknown",
    "axis": "contentType",
    "slug": "unknown",
    "label": "未标注类型",
    "labelZh": "未标注类型",
    "aliases": [],
    "wireframeDeclaredCount": null,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "contentType:video",
    "axis": "contentType",
    "slug": "video",
    "label": "视频",
    "labelZh": "视频",
    "aliases": [],
    "wireframeDeclaredCount": 479,
    "appearsOn": [
      "l2"
    ]
  },
  {
    "id": "model:gpt-image",
    "axis": "model",
    "slug": "gpt-image",
    "label": "GPT Image",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 115,
    "appearsOn": [
      "l1",
      "l2"
    ]
  },
  {
    "id": "model:gpt-image-2",
    "axis": "model",
    "slug": "gpt-image-2",
    "label": "GPT Image 2",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 50,
    "appearsOn": [
      "l2",
      "l4"
    ]
  },
  {
    "id": "model:higgsfield-soul",
    "axis": "model",
    "slug": "higgsfield-soul",
    "label": "Higgsfield Soul",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 118,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "model:kling",
    "axis": "model",
    "slug": "kling",
    "label": "Kling",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 76,
    "appearsOn": [
      "l1",
      "l2"
    ]
  },
  {
    "id": "model:nano-banana",
    "axis": "model",
    "slug": "nano-banana",
    "label": "Nano Banana",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 218,
    "appearsOn": [
      "l1",
      "l2"
    ]
  },
  {
    "id": "model:nano-banana-2",
    "axis": "model",
    "slug": "nano-banana-2",
    "label": "Nano Banana 2",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 40,
    "appearsOn": [
      "l2"
    ]
  },
  {
    "id": "model:nano-banana-pro",
    "axis": "model",
    "slug": "nano-banana-pro",
    "label": "Nano Banana Pro",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 136,
    "appearsOn": [
      "l2",
      "l3"
    ]
  },
  {
    "id": "model:seedance",
    "axis": "model",
    "slug": "seedance",
    "label": "Seedance",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 272,
    "appearsOn": [
      "l1",
      "l2"
    ]
  },
  {
    "id": "model:sora",
    "axis": "model",
    "slug": "sora",
    "label": "Sora",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 13,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "model:veo",
    "axis": "model",
    "slug": "veo",
    "label": "Veo",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 26,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "model:wan",
    "axis": "model",
    "slug": "wan",
    "label": "Wan",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 11,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "style:anime-illustrated",
    "axis": "style",
    "slug": "anime-illustrated",
    "label": "Anime / illustrated",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 126,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "style:cinematic",
    "axis": "style",
    "slug": "cinematic",
    "label": "Cinematic",
    "labelZh": "电影感",
    "aliases": [],
    "wireframeDeclaredCount": 416,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "style:luxury",
    "axis": "style",
    "slug": "luxury",
    "label": "Luxury",
    "labelZh": "奢华风",
    "aliases": [],
    "wireframeDeclaredCount": 179,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "style:photorealistic",
    "axis": "style",
    "slug": "photorealistic",
    "label": "Photorealistic",
    "labelZh": "写实风",
    "aliases": [
      "超写实"
    ],
    "wireframeDeclaredCount": 393,
    "appearsOn": [
      "l1",
      "l2",
      "l3",
      "l4"
    ]
  },
  {
    "id": "style:retro-vintage",
    "axis": "style",
    "slug": "retro-vintage",
    "label": "Retro / vintage",
    "labelZh": "复古风",
    "aliases": [],
    "wireframeDeclaredCount": 180,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "style:sci-fi-cyberpunk",
    "axis": "style",
    "slug": "sci-fi-cyberpunk",
    "label": "Sci-fi / cyberpunk",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 117,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "style:surreal-fantasy",
    "axis": "style",
    "slug": "surreal-fantasy",
    "label": "Surreal / fantasy",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 85,
    "appearsOn": [
      "l1",
      "l2"
    ]
  },
  {
    "id": "subject:architecture-interior",
    "axis": "subject",
    "slug": "architecture-interior",
    "label": "Architecture / interior",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 33,
    "appearsOn": [
      "l2",
      "l3"
    ]
  },
  {
    "id": "subject:food-drink",
    "axis": "subject",
    "slug": "food-drink",
    "label": "Food / drink",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 9,
    "appearsOn": [
      "l2",
      "l3"
    ]
  },
  {
    "id": "subject:person-portrait",
    "axis": "subject",
    "slug": "person-portrait",
    "label": "Person / portrait",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 215,
    "appearsOn": [
      "l2",
      "l3"
    ]
  },
  {
    "id": "subject:product",
    "axis": "subject",
    "slug": "product",
    "label": "Product",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 12,
    "appearsOn": [
      "l2",
      "l3"
    ]
  },
  {
    "id": "subject:vehicle",
    "axis": "subject",
    "slug": "vehicle",
    "label": "Vehicle",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 9,
    "appearsOn": [
      "l2",
      "l3"
    ]
  },
  {
    "id": "technique:camera-movement-shot-language",
    "axis": "technique",
    "slug": "camera-movement-shot-language",
    "label": "Camera movement / shot language",
    "labelZh": "镜头运动",
    "aliases": [
      "Camera / shot language",
      "Camera movement"
    ],
    "wireframeDeclaredCount": 698,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "technique:character-consistency",
    "axis": "technique",
    "slug": "character-consistency",
    "label": "Character consistency",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 41,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "technique:image-to-video",
    "axis": "technique",
    "slug": "image-to-video",
    "label": "Image-to-video",
    "labelZh": "图生视频",
    "aliases": [],
    "wireframeDeclaredCount": 69,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "technique:lip-sync-dialogue",
    "axis": "technique",
    "slug": "lip-sync-dialogue",
    "label": "Lip sync / dialogue",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 75,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "technique:miniature-photography",
    "axis": "technique",
    "slug": "miniature-photography",
    "label": "微缩摄影",
    "labelZh": "微缩摄影",
    "aliases": [],
    "wireframeDeclaredCount": null,
    "appearsOn": [
      "l4"
    ]
  },
  {
    "id": "technique:multi-shot-storyboard",
    "axis": "technique",
    "slug": "multi-shot-storyboard",
    "label": "Multi-shot / storyboard",
    "labelZh": "分镜",
    "aliases": [],
    "wireframeDeclaredCount": 174,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "technique:text-to-video",
    "axis": "technique",
    "slug": "text-to-video",
    "label": "Text-to-video",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 8,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "technique:transition-morph-match-cut",
    "axis": "technique",
    "slug": "transition-morph-match-cut",
    "label": "Transition / morph / match cut",
    "labelZh": "转场",
    "aliases": [
      "Transition / morph"
    ],
    "wireframeDeclaredCount": 110,
    "appearsOn": [
      "l1"
    ]
  },
  {
    "id": "useCase:advertising",
    "axis": "useCase",
    "slug": "advertising",
    "label": "Advertising",
    "labelZh": "广告",
    "aliases": [],
    "wireframeDeclaredCount": 133,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "useCase:automotive",
    "axis": "useCase",
    "slug": "automotive",
    "label": "Automotive",
    "labelZh": "汽车",
    "aliases": [],
    "wireframeDeclaredCount": 68,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "useCase:beauty",
    "axis": "useCase",
    "slug": "beauty",
    "label": "Beauty",
    "labelZh": "美妆",
    "aliases": [],
    "wireframeDeclaredCount": 149,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "useCase:fashion",
    "axis": "useCase",
    "slug": "fashion",
    "label": "Fashion",
    "labelZh": "时尚",
    "aliases": [],
    "wireframeDeclaredCount": 162,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "useCase:food-beverage",
    "axis": "useCase",
    "slug": "food-beverage",
    "label": "Food & beverage",
    "labelZh": "餐饮",
    "aliases": [],
    "wireframeDeclaredCount": 81,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  },
  {
    "id": "useCase:product-marketing",
    "axis": "useCase",
    "slug": "product-marketing",
    "label": "Product marketing",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 45,
    "appearsOn": [
      "l1",
      "l2"
    ]
  },
  {
    "id": "useCase:ugc",
    "axis": "useCase",
    "slug": "ugc",
    "label": "UGC",
    "labelZh": null,
    "aliases": [],
    "wireframeDeclaredCount": 17,
    "appearsOn": [
      "l1",
      "l2"
    ]
  },
  {
    "id": "useCase:web-motion-design",
    "axis": "useCase",
    "slug": "web-motion-design",
    "label": "Web & motion design",
    "labelZh": null,
    "aliases": [
      "Web & motion"
    ],
    "wireframeDeclaredCount": 25,
    "appearsOn": [
      "l1",
      "l2",
      "l3"
    ]
  }
];
