import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
const require=createRequire(new URL('../../package.json',import.meta.url));
const {chromium}=require('@playwright/test');
const AxeBuilder=require('@axe-core/playwright').default;
const base='http://127.0.0.1:3000', dir=new URL('.',import.meta.url).pathname;
const paths=['/zh-CN/prompts','/zh-CN/prompts/image','/zh-CN/prompts/video','/zh-CN/prompts/model-families/nano-banana','/zh-CN/prompts/use-cases/beauty','/zh-CN/prompts/styles/photorealistic','/zh-CN/prompts/concept-2008952931484098637'];
const browser=await chromium.launch({headless:true});const results=[];
try{for(const width of [375,1440]){const context=await browser.newContext({viewport:{width,height:900},deviceScaleFactor:1});for(const route of paths){const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const response=await page.goto(base+route,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);const metrics=await page.evaluate(()=>({title:document.title,overflow:document.documentElement.scrollWidth>innerWidth,htmlLang:document.documentElement.lang,bodyLang:document.body.lang,h1:[...document.querySelectorAll('h1')].map(e=>e.textContent),images:[...document.images].map(i=>({src:i.currentSrc,alt:i.alt,loaded:i.complete&&i.naturalWidth>0,loading:i.loading,width:i.naturalWidth,height:i.naturalHeight,displayWidth:i.getBoundingClientRect().width})),videos:document.querySelectorAll('video').length}));let violations=[];if(width===375&&[paths[0],paths[4],paths[5]].includes(route)){const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();violations=axe.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,helpUrl:v.helpUrl,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))}));}if(width===375&&[paths[0],paths[3],paths[5]].includes(route))await page.screenshot({path:dir+`screen-${route.split('/').pop()}-${width}.png`});results.push({route,width,status:response.status(),...metrics,errors,violations});console.log(width,route,metrics.overflow,violations.map(v=>v.id));await page.close();}await context.close();}}finally{await browser.close();}await fs.writeFile(dir+'browser.json',JSON.stringify(results,null,2));
