'use client';
import {useState} from 'react';
import type {Prompt} from '@/lib/catalog/types';
export type {Prompt};
export const NONE='__none__';
export function options(rows:Prompt[],axis:'models'|'useCases'){
const map=new Map<string,{slug:string,label:string,count:number}>();
for(const p of rows) for(const r of p[axis].length?p[axis]:[{slug:NONE,label:axis==='models'?'No model named':'Unfiled'}]) map.set(r.slug,{slug:r.slug,label:r.label,count:(map.get(r.slug)?.count||0)+1});
return [...map.values()].sort((a,b)=>b.count-a.count);
}
export function matches(p:Prompt,axis:'models'|'useCases',value:string){return !value||(value===NONE?!p[axis].length:p[axis].some(r=>r.slug===value))}
export function Photo({p,priority=false}:{p:Prompt;priority?:boolean}){const [failed,setFailed]=useState(false);return p.img&&!failed?<img src={p.img} alt={`Result: ${p.title}`} width={600} height={600} loading={priority?'eager':'lazy'} referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<span className="no-photo">{failed?'Source image unavailable':'No image on the source post'}</span>}
export function Card({p}:{p:Prompt}){return <article className="prompt-card"><a className="photo-link" href={p.href} aria-label={`Open ${p.title}`}><Photo p={p}/></a><div className="card-body"><p className="micro">{p.models.map(m=>m.label).join(' · ')||'No model named'}</p><h3><a href={p.href}>{p.title}</a></h3><p className="byline">{p.handle||'Unattributed'}{p.likes!==null?` · ${p.likes.toLocaleString('en-US')} likes`:''}</p><a className="text-cta" href={p.href}>Generate image <span aria-hidden="true">↗</span></a></div></article>}
export function Empty({clear}:{clear:()=>void}){return <div className="empty"><h2>No image prompts match.</h2><p>Try another model or task, or clear your filters.</p><button className="button" onClick={clear}>Clear filters</button></div>}
export function useFilters(rows:Prompt[]){const [q,setQ]=useState(''),[model,setModel]=useState(''),[task,setTask]=useState(''); const found=rows.filter(p=>matches(p,'models',model)&&matches(p,'useCases',task)&&[p.title,p.prompt,p.handle,...p.models.map(m=>m.label),...p.useCases.map(m=>m.label)].join(' ').toLowerCase().includes(q.toLowerCase().trim())); return {q,setQ,model,setModel,task,setTask,found,clear(){setQ('');setModel('');setTask('')}}}
export function Controls({rows,f,task=true}:{rows:Prompt[];f:ReturnType<typeof useFilters>;task?:boolean}){return <form className="controls" onSubmit={e=>e.preventDefault()}><label className="search-label">Search image prompts<input type="search" value={f.q} onChange={e=>f.setQ(e.target.value)} placeholder="Search titles, prompts or creators…" autoComplete="off" spellCheck={false}/></label><label>Model<select value={f.model} onChange={e=>f.setModel(e.target.value)}><option value="">All models</option>{options(rows,'models').map(m=><option key={m.slug} value={m.slug}>{m.label} ({m.count})</option>)}</select></label>{task&&<label>Task<select value={f.task} onChange={e=>f.setTask(e.target.value)}><option value="">All tasks</option>{options(rows,'useCases').map(m=><option key={m.slug} value={m.slug}>{m.label} ({m.count})</option>)}</select></label>}<button type="button" className="clear" onClick={f.clear}>Clear filters</button></form>}
export function Shell({rows,note,children}:{rows:Prompt[];note:string;children:React.ReactNode}){return <><a className="skip" href="#main">Skip to content</a><header className="site-nav"><a className="brand" href="http://127.0.0.1:3000/zh-CN/prompts">Prompt Library</a><nav aria-label="Primary"><a href="http://127.0.0.1:3000/zh-CN/prompts">Home</a><a href="http://127.0.0.1:3000/zh-CN/prompts/image" aria-current="page">Images</a><a href="http://127.0.0.1:3000/zh-CN/prompts/video">Videos</a><a href="http://127.0.0.1:3000/zh-CN/prompts#models">Models</a></nav></header><main id="main" className="page"><nav className="crumbs" aria-label="Breadcrumb"><a href="http://127.0.0.1:3000/zh-CN/prompts">Prompt Library</a><span>/</span><span>Images</span></nav><div className="heading"><div><p className="eyebrow">The image library</p><h1>Image prompts</h1><p className="intro">{note}</p></div><p className="inventory"><strong>{rows.length.toString().padStart(2,'0')}</strong><span>image prompts<br/>credited to their creators</span></p></div>{children}<footer className="footer"><span>Prompt Library</span><p>Prompts remain the property of their authors. Every page credits the source.</p></footer></main></>}
